### PR TITLE
QT screenshot fix

### PR DESCRIPTION
**Pull request by AlexanderGrant1**
Added QT and updated Titanium page

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
@AlexanderGrant1 - is this ready for merge? It still looks like there are issues:

http://alexandergrant1.github.io/PropertyCross-Site/qt/

**Comment by bdimitrov-SL** [comment]
@ColinEberhardt The code is ready to merge, but the Github Jekyll build fails for some reason (no specific error) and that's why you can't see the change on the page. I did an experiment on my fork that has the Crosslight page update that was already merged and we know it works.  I added an empty commit just to trigger the gh-pages build and it failed for me too, even though there are no changes to the code whatsoever. I suspect it may be a problem with the twitter-bootstrap dependency as it was giving me trouble on my local build as well. If you don't feel like risking a merge without having a successful build on the fork we can wait until we have the new version of bootstrap added as Node dependency and get rid of the twitter-bootstrap git module altogether.

**Comment by ColinEberhardt** [comment]
Hi @bdimitrov-SL I risked it, and pushed that commit to `gh-pages`, but unfortunately it failed for me too. Submodules shouldn't be a problem:

https://help.github.com/articles/using-submodules-with-pages/

Unfortunately this generic failure message is something I've seen before. Fixing it is not much fun, involving trial and error.

Hence my thoughts here: https://github.com/ColinEberhardt/PropertyCross-Site/issues/18

If this is just going to eat up time, feel free to leave adding QT until you have a new build and / or the updated website design.

**Comment by ColinEberhardt** [comment]
Here's the commit: https://github.com/ColinEberhardt/PropertyCross-Site/commit/59e1814886704a112428e48047b565ce3001e346

As you can see the site hasn't re-built.

**Pull request closed without merging**
