### PR TITLE
Update JQueryMobile website pages

### PR DESCRIPTION
**Pull request by matthewdunsdon**
Only been able to upload Android and Windows Phone screenshots.

### CODE REVIEW

**Comment by matthewdunsdon** [comment]
For screenshots, see https://github.com/matthewdunsdon/PropertyCross-Site/commit/c999bf47bd5df52c5ccd9f7cd616a58bdcabb4cc (do not include iOS screenshots)

**Comment by matthewdunsdon** [comment]
Pull request dependant on iOS screenshots and JQueryMobile readme update for website

**Comment by matthewdunsdon** [comment]
JQueryMobile overview text has been updated.

@ColinEberhardt Is it the case the the PR is just waiting on iOS screenshots?

**Comment by matthewdunsdon** [comment]
iOS screenshots updated.  All looks good to me. :smile:

**Comment by ColinEberhardt** [comment]
Great job - thanks for this :-)

**Pull request merged**
